# Generated by Django 5.2.7 on 2025-10-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='idempotencykey',
            name='payments_id_key_1ccb8e_idx',
        ),
        migrations.RemoveField(
            model_name='idempotencykey',
            name='user',
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['key'], name='payments_id_key_4e56e0_idx'),
        ),
    ]
